- name: create tmp and clone app repo
  block:
    - name: Create the tmp directory
      file:
        path: "{{role_path}}/tmp"
        state: directory

    - name: clone the repo with apps knowledge
      git:
        #repo: git@github.com:arunhotra/app-repo.git
        repo: https://github.com/arunhotra/app_repo_via_post.git
        dest: "{{ role_path }}/tmp/app-inputs"
        accept_hostkey: true
  run_once: true
  tags:
    - buildApp
